<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INLEN6239019998" failures="2" tests="10" name="RetryMultipleFailedCases" time="59.725" errors="0" timestamp="2023-02-03T16:43:43 IST">
  <testcase classname="testexecution.HomePageTest" name="validateHotelTitle" time="0.011"/>
  <testcase classname="testexecution.DemoTest" name="test1" time="0.002"/>
  <testcase classname="testexecution.DemoTest" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testexecution.DemoTest" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testexecution.DemoTest" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testexecution.DemoTest" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testexecution.DemoTest.test2(DemoTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testexecution.DemoTest" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="testexecution.DemoTest" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="testexecution.DemoTest" name="test3" time="0.0">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="testexecution.DemoTest" name="test3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testexecution.DemoTest.test3(DemoTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- RetryMultipleFailedCases -->
